---
- name: configure ldap domain
  debconf:
    name: slapd
    question: slapd/domain
    vtype: string
    value: "{{ ldap_domain }}"

- name: configure ldap organization
  debconf:
    name: slapd
    question: shared/organization
    vtype: string
    value: "{{ ldap_domain }}"

# cannot retrieve original value and will not change password without force, so
# report no change.
- name: configure ldap passwd 1
  debconf:
    name: slapd
    question: slapd/password1
    vtype: password
    value: "{{ ldap_admin_password }}"
  changed_when: false

# cannot retrieve original value and will not change password without force, so
# report no change.
- name: configure ldap passwd 2
  debconf:
    name: slapd
    question: slapd/password2
    vtype: password
    value: "{{ ldap_admin_password }}"
  changed_when: false

- name: ensure required base packages are present
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - slapd
    - ldap-utils
    - ldapscripts

# FIXME: dpkg seems broken
#- name: enforce desired slapd package configuration
#  dpkg_reconfigure:
#    pkg: slapd
#    answers:
#      slapd/domain: "{{ ldap_domain }}"
#      slapd/password1: "{{ ldap_admin_password }}"
#      slapd/password2: "{{ ldap_admin_password }}"

- name: update /etc/default/slapd from template
  template:
    src: etc/default/slapd
    dest: /etc/default/slapd
    owner: root
    group: root
    mode: 0644
  notify:
    - restart slapd

- name: ensure slapd is started and enabled
  service:
    name: slapd
    state: started
    enabled: yes
    
- name: update /etc/ldap/certinfo.ldif from template
  template:
    src: etc/ldap/certinfo.ldif
    dest: /etc/ldap/certinfo.ldif
    owner: root
    group: root
    mode: 0644

- name: ensure ssl key and certificate are configured when specified
  shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f /etc/ldap/certinfo.ldif
  register: add_certificate_configuration
  changed_when: add_certificate_configuration.rc == 0
  when: slapd_ssl_cert_file != "" and slapd_ssl_key_file != "" 

- name: ensure expected organizational units are present
  ldap:
    bind_dn: cn=admin,{{ ldap_base_dn }}
    bind_password: "{{ ldap_admin_password }}" 
    entry_dn: ou={{ item }},{{ ldap_base_dn }}
    attrs:
      - objectClass: organizationalUnit
      - ou: "{{ item }}"
    state: present
  with_items:
    - Users
    - Groups
    - Machines

- name: update /etc/ldapscripts/ldapscripts.conf from template
  template:
    src: etc/ldapscripts/ldapscripts.conf
    dest: /etc/ldapscripts/ldapscripts.conf
    owner: root
    group: root
    mode: 0644

- name: update /etc/ldapscripts/ldapscripts.passwd from template
  template:
    src: etc/ldapscripts/ldapscripts.passwd
    dest: /etc/ldapscripts/ldapscripts.passwd
    owner: root
    group: root
    mode: 0600

