---
- name: configure ldap domain
  debconf:
    name: slapd
    question: slapd/domain
    vtype: string
    value: "{{ slapd_domain }}"

- name: configure ldap organization
  debconf:
    name: slapd
    question: shared/organization
    vtype: string
    value: "{{ slapd_domain }}"

# can we just force password here?
- name: configure ldap passwd 1
  debconf:
    name: slapd
    question: slapd/password1
    vtype: password
    value: "{{ slapd_admin_password }}"
  changed_when: false

- name: configure ldap passwd 2
  debconf:
    name: slapd
    question: slapd/password2
    vtype: password
    value: "{{ slapd_admin_password }}"
  changed_when: false

- name: ensure required base packages are present
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - slapd
    - ldap-utils
    - ldapscripts

- name: update /etc/ldapscripts/ldapscripts.conf from template
  template:
    src: templates/etc/ldapscripts/ldapscripts.conf
    dest: /etc/ldapscripts/ldapscripts.conf
    owner: root
    group: root
    mode: 0644

- name: update /etc/ldapscripts/ldapscripts.passwd from template
  template:
    src: templates/etc/ldapscripts/ldapscripts.passwd
    dest: /etc/ldapscripts/ldapscripts.passwd
    owner: root
    group: root
    mode: 0600

- name: ensure slapd is started and enabled
  service:
    name: slapd
    state: started
    enabled: yes
    
- name: ensure expected organizational units are present
  ldap:
    ldap_uri: ldapi:///
    entry_dn: ou={{ item }},{{ slapd_base_dn }}
    attrs:
      - objectClass: organizationalUnit
      - ou: "{{ item }}"
    state: present
  with_items:
    - Users
    - Groups
    - Machines
