---
- name: ensure required base packages are present
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - slapd
    - ldap-utils
    - ldapscripts

- name: update /etc/ldapscripts/ldapscripts.conf from template
  template:
    src: templates/etc/ldapscripts/ldapscripts.conf
    dest: /etc/ldapscripts/ldapscripts.conf
    owner: root
    group: root
    mode: 0644

- name: update /etc/ldapscripts/ldapscripts.passwd from template
  template:
    src: templates/etc/ldapscripts/ldapscripts.passwd
    dest: /etc/ldapscripts/ldapscripts.passwd
    owner: root
    group: root
    mode: 0600

- name: ensure slapd is started and enabled
  service:
    name: slapd
    state: started
    enabled: yes
    
- name: ensure root dn and root password are set to desired values
  ldap:
    entry_dn: olcDatabase={1}hdb,cn=config
    attrs:
      - olcRootDN: "{{ slapd_admin_dn }}"
      - olcRootPW: "{{ slapd_admin_password }}"
    state: present

- name: ensure expected organizational units are present
  ldap:
    entry_dn: ou={{ item }},{{ ldap_base_dn }}
    attrs:
      - objectClass: organizationalUnit
      - ou: "{{ item }}"
    state: present
  with_items:
    - Users
    - Groups
    - Machines
